# Generated by Django 5.0.6 on 2024-06-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artiste', models.CharField(max_length=500)),
                ('artist_image', models.ImageField(upload_to='art/')),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('audio_file', models.FileField(upload_to='musics/')),
                ('cover_image', models.ImageField(upload_to='music_images/')),
            ],
        ),
    ]
