# Generated by Django 5.0.6 on 2024-06-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('id',)},
        ),
    ]
